name: ${rootProject.name}
version: ${rootProject.version}
api-version: 1.19
main: ${plugin_main}
libraries:
  - io.github.monun:kommand-core:3.1.2
  - org.jetbrains.exposed:exposed-core:0.41.1
  - org.jetbrains.exposed:exposed-jdbc:0.41.1